blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/tenshiku/DiscOBS/wiki
    about: Check the wiki for setup guides and troubleshooting
  - name: 💬 Discussions
    url: https://github.com/tenshiku/DiscOBS/discussions
    about: Ask questions and share ideas with the community